# Generated by Django 5.1.7 on 2025-03-11 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('traffic', 'Traffic'), ('help', 'Help'), ('ambulance', 'Ambulance')], max_length=20, verbose_name='نوع البلاغ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل البلاغ')),
                ('lng', models.CharField(max_length=50, verbose_name='خط الطول')),
                ('lat', models.CharField(max_length=50, verbose_name='خط العرض')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Resolved')], default=0, verbose_name='حالة البلاغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'بلاغ',
                'verbose_name_plural': 'البلاغات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attechment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%s/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.report')),
            ],
        ),
    ]
