# Generated by Django 5.1.7 on 2025-03-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_report_attechment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(blank=True, default=0, verbose_name='حالة البلاغ'),
        ),
    ]
