# Generated by Django 5.1.7 on 2025-03-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attechment',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/%s/'),
        ),
    ]
