# Generated by Django 5.1.7 on 2025-03-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_attechment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('traffic', 'Traffic'), ('help', 'Help'), ('ambulance', 'Ambulance')], max_length=50),
        ),
    ]
