# Generated by Django 5.1.7 on 2025-03-30 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_customuser_type_alter_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإعلان')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل الإعلان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='صورة الإعلان')),
                ('type_ads', models.IntegerField(choices=[(0, 'دارة التطبيق'), (1, 'مرور'), (2, 'الإسعاف'), (3, 'النجدة'), (4, 'المطافئ')], verbose_name='نوع الإعلان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الناشر')),
            ],
        ),
    ]
