# Generated by Django 5.1.7 on 2025-03-30 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الناشر'),
        ),
    ]
