# Generated by Django 5.1.7 on 2025-04-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_ads_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='ads/', verbose_name='صورة الإعلان'),
        ),
    ]
