# Generated by Django 5.1.7 on 2025-04-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_ads_options_alter_ads_type_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('traffic', 'بلاغ مروري'), ('help', 'بلاغ نجدة'), ('ambulance', 'بلاغ اسعاف'), ('fire', 'بلاغ مطافئ')], max_length=20, verbose_name='نوع البلاغ'),
        ),
    ]
